### PR TITLE
Upgrade to react v17

### PR DESCRIPTION
**Pull request by msitu**
- Enzyme adaptmer must also be upgraded.
- all tests that arent' skipped still pass.

### CODE REVIEW

**Comment by msitu** [comment]
I changed earthscope's package.json to have the following dependencies:
```
     "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-mapbox-gl": "msitu/react-mapbox-gl",
```

And the UI loaded locally!

react-17

**Comment by snickell** [comment]
Oh nice! Does your local normally have those black bars for some reason? I don't get those, not sure if its react 17 side effects or what? @BeccaKRobinson you seen those?

**Comment by msitu** [comment]
the styling does look a little different... i'll have to take a look at the CSS to see if something is broken

**Comment by msitu** [comment]
> Oh nice! Does your local normally have those black bars for some reason? I don't get those, not sure if its react 17 side effects or what? @BeccaKRobinson you seen those?

I had to `npm install` again to get the mapbox-gl css. everything looks good again

**Pull request merged**
